apps/central/urls.py
from django.urls import path

from .views import (
    IndexView,
    CreateView,
    EventView,
    ArchiveView,
    ReferenceView,

    LoginView,
    LogoutView,
)


app_name = 'central'
urlpatterns = (
    path('', IndexView.as_view(), name='index'),
    path('create/', CreateView.as_view(), name='create'),
    path('event/<int:pk>/', EventView.as_view(), name='event'),
    path('archive/', ArchiveView.as_view(), name='archive'),
    path('reference/', ReferenceView.as_view(), name='reference'),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
)

conf/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.central.urls'), name='central'),
]

apps/central/models.py
from django.db import models


class Event(models.Model):

    EVENT_TYPE_CHOICES = (
        ('0', 'Конференции'),
        ('1', 'Монографии'),
        ('2', 'борники статей'),
    )
    EVENT_TOPIC_CHOICES = (
        ('0', 'Архиология'),
        ('1', 'Архитектура, Строительство'),
    )
    EVENT_FORM_CHOICES = (
        ('0', 'Заочная'),
        ('1', 'Очная'),
        ('2', 'Очно-заочная'),
    )

    name = models.CharField(max_length=255, verbose_name='Название мероприятия')
    event_type = models.CharField(max_length=30, choices=EVENT_TYPE_CHOICES, verbose_name='Тематика')
    topic = models.CharField(max_length=255, choices=EVENT_TOPIC_CHOICES, verbose_name='Тип мероприятия')
    event_form = models.CharField(max_length=30, choices=EVENT_FORM_CHOICES, verbose_name='Форма участия')

    start_date = models.DateTimeField(verbose_name='Дата начала')
    end_date = models.DateTimeField(verbose_name='Дата окончания')

    description = models.TextField(verbose_name='Подробное описание')
    deadline = models.DateTimeField(verbose_name='Срок подачи заявок')

    organizers = models.TextField(verbose_name='Организаторы')
    contact_info = models.TextField(verbose_name='Контактная информация', default='')
    email = models.EmailField(verbose_name='Адрес электронной почты')
    country = models.CharField(max_length=30, verbose_name='Страна', default='')
    city = models.CharField(max_length=30, verbose_name='Город', default='')

apps/central/forms.py
from django.forms import ModelForm, DateInput, TextInput, Select, Textarea, EmailInput

from .models import Event


class DateInputWidget(DateInput):
    input_type = 'date'


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = '__all__'
        widgets = {
            'start_date': DateInputWidget(attrs={'class': 'form-control'}),
            'end_date': DateInputWidget(attrs={'class': 'form-control'}),
            'deadline': DateInputWidget(attrs={'class': 'form-control'}),
            'name': TextInput(attrs={'class': 'form-control'}),
            'event_type': Select(attrs={'class': 'form-control'}),
            'topic': Select(attrs={'class': 'form-control'}),
            'event_form': Select(attrs={'class': 'form-control'}),
            'city': TextInput(attrs={'class': 'form-control'}),
            'country': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'organizers': Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'contact_info': Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'email': EmailInput(attrs={'class': 'form-control'}),
        }

apps/central/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Event
from .forms import EventForm


class EventView(View):
    def get(self, request, pk):
        event = Event.objects.get(pk=pk)
        return render(request, 'central/event.html', {'event': event})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('central:index')


class LoginView(View):
    def get(self, request):
        return render(request, 'central/login.html')

    def post(self, request):

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
        else:
            print('lol')
        print(user)
        return render(request, 'central/login.html')


class IndexView(View):
    def get(self, request):
        events = Event.objects.all()
        return render(request, 'central/index.html', {'events': events})


class ReferenceView(View):
    def get(self, request):
        events = Event.objects.all()
        return render(request, 'central/reference.html', {'events': events})


class ArchiveView(View):
    def get(self, request):
        events = Event.objects.all()
        return render(request, 'central/archive.html', {'events': events})


class CreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = EventForm()
        return render(request, 'central/create.html', {'form': form})

    def post(self, request):
        form = EventForm(request.POST)
        print(request.POST)
        if form.is_valid():
            form.save()
        else:
            print(form.errors)

        return render(request, 'central/create.html', {'form': EventForm()})

apps/central/templates/central/archive.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
<p>Архив</p>
    {% for event in events %}
    <div class="card py-2 my-2">
        <p>{{ event.start_date.date }} — {{ event.end_date.date }}, срок заявок: {{ event.deadline.date }}</p>
        <a href="{% url 'central:event' event.pk %}"><h5>{{ event.name }}</h5></a>
        <strong>{{ event.country }}, {{ event.city }}</strong>
        <p>Организаторы: {{ event.organizers }}</p>
    </div>

    {% endfor %}
</div>

{% endblock %}

apps/central/templates/central/create.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col-md-6">
        <p>Create</p>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="fieldWrapper">
                    <div class="form-group">
                        {{ field.errors }}
                        {{ field.label_tag }} {{ field }}
                        {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            <button class="btn btn-primary">Создать событие</button>
        </form>
    </div>
</div>
{% endblock %}

apps/central/templates/central/event.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

    <span>{{ event.description|linebreaksbr }}</span>

    <p>Последний день подачи заявки: {{ event.deadline.date }}</p>

    <p>Организаторы: {{ event.organizers }}</p>

    <p>Контактная информация: {{ event.contact_info }}</p>

    <p>Эл. почта: {{ event.email }}</p>

</div>

{% endblock %}

apps/central/templates/central/index.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
<p>Index</p>
    {% for event in events %}
    <div class="card py-2 my-2">
        <p>{{ event.start_date.date }} — {{ event.end_date.date }}, срок заявок: {{ event.deadline.date }}</p>
        <a href="{% url 'central:event' event.pk %}"><h5>{{ event.name }}</h5></a>
        <strong>{{ event.country }}, {{ event.city }}</strong>
        <p>Организаторы: {{ event.organizers }}</p>
    </div>

    {% endfor %}
</div>

{% endblock %}

apps/central/templates/central/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 my-4">
            <form method="post">
              {% csrf_token %}
              <div class="form-group">
                <label for="exampleInputEmail1">Логин</label>
                <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Введите логин">
                <small id="emailHelp" class="form-text text-muted">Никому не говорите пароль.</small>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Пароль</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Пароль">
              </div>
              <button type="submit" class="btn btn-primary">Войти</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

apps/central/templates/central/reference.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h3>Справка</h3>
На каких условиях размещается информация о конференциях на сайте "Конференции.ru"?
Информация о научных мероприятиях размещается на сайте БЕСПЛАТНО. Сайт размещает только информацию о научных или околонаучных мероприятиях.

Как быстро на сайте публикуется информация о конференциях?
На сайте информация видна сразу после загрузки ее пользователем. Неотмодерированная информация выделена цветом и специальным сообщением. Сроки модерации обычно составляют от 5 минуты до 1 суток. Невыполнение правил регистрации мероприятия существенно замедлит рассмотрением информации модератором.

Зачем регистрироваться на сайте?
Зарегистрированный пользователь имеет некоторые преимущества, а именно:
- При внесении информации имеет право последующего редактирования.
- При внесении информации не потребуется вводить код подтверждения.
- Зарегистрированный пользователь в своем профайле может заполнить форму дополнительной информации, которая используется для автоматического наполнения форм заявок на страницах конференций.
- Только зарегистрированным пользователям доступна рассылка добавлений конференций за неделю с выбором любого количества тематик.
- Зарегистрированный пользователь имеет возможность отправления быстрых сообщений со страниц мероприятий.

Есть ли какие правила регистрации конференции чтобы избегать ошибок при внесении информации?
На странице добавления мероприятия есть ссылка на рекомендации при добавлении информации в Каталог. Подробнее...

Веб-форма заявок на участие в конференции: как она выглядит и как ее включить?
Веб-форма заявок имеет стандартный вид для всех конференций нашего Каталога. Включается использование данной формы при регистрации конференции или редактировании информации.  При использовании веб-формы пользователем на адрес эл. почты оргкомитета высылается заявка в виде текста письма, а также в виде вложенного текстового cvs-файла. В перспективе развития Каталога cvs-файл будет использоваться для автоматической регистрации пользователей специальной программой. Вид веб-формы представлен здесь. При активации нашей формы заявок, имеется возможность использования дополнительных полей, а также возможность редактировать названия всех полей.
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    {% include 'includes/_navbar.html' %}
    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/includes/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container"><a class="navbar-brand" href="/">Конференции</a>
    <div class="d-flex ml-auto">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#globalNavbar" aria-controls="globalNavbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    </div>
    <div class="collapse navbar-collapse" id="globalNavbar">
      <ul class="navbar-nav mr-auto order-1">
        <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'central:create' %}">Создать</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'central:archive' %}">Архив</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'central:reference' %}">Справка</a>
        </li>
      </ul>
      <ul class="navbar-nav d-none d-lg-flex ml-2 order-3">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <p class="navbar-text">{{ request.user.username }}</p>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'central:logout' %}">Выйти</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'central:login' %}">Войти</a>
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav d-lg-none">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <p class="navbar-text">{{ request.user.username }}</p>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'central:logout' %}">Выйти</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'central:login' %}">Войти</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>


<!--<nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--    <div class="container">-->
<!--      -->
<!--      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--      </button>-->
<!--      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">-->
<!--          <ul class="navbar-nav mr-auto">-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="#">Home</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="{% url 'central:create' %}">Создать</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="{% url 'central:archive' %}">Архив</a>-->
<!--            </li>-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="{% url 'central:reference' %}">Справка</a>-->
<!--            </li>-->
<!--          </ul>-->
<!--          <ul class="navbar-nav">-->
<!--            {% if request.user.is_authenticated %}-->
<!--            <li class="nav-item">-->
<!--              <p class="nav-link disabled">{{ request.user.username }}</p>-->
<!--            </li>-->
<!--            {% endif %}-->
<!--            <li class="nav-item">-->
<!--            {% if request.user.is_authenticated %}-->
<!--              <a class="nav-link" href="{% url 'central:logout' %}">Выйти</a>-->
<!--            {% else %}-->
<!--              <a class="nav-link" href="{% url 'central:login' %}">Войти</a>-->
<!--            {% endif %}-->
<!--            </li>-->
<!--          </ul>-->
<!--      </div>-->
<!--    </div>-->
<!--</nav>-->